# Generated by Django 5.2.11 on 2026-05-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_boardmember_is_emeritus'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoconedition',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='djangoconedition',
            name='highlight',
            field=models.TextField(blank=True, help_text='One-line summary shown in the edition card and timeline.'),
        ),
    ]
